print("Today's date: 2025-10-15")
print("How I'm feeling right now: excited, curious, and motivated")
print("What I want to accomplish by learning to code: build useful projects, solve real problems, and become a confident developer")
print("Message to my future self: Keep learning, ship code often, be kind to your past self, and never stop exploring new ideas.")
print("Favorite emoji: 🚀")
